Receive use_docker flag from the cli
aws-cloudformation/cloudformation-cli-python-plugin pull request #121
Opened 2020-09-11 22:44 UTC by chuchocd85

*Issue #, if available:*

*Description of changes:*
Add ability to consume the use docker flag from the `cloudformation-cli`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-14 17:32 UTC, jotompki requested changes
Is there a way to prompt for the arguments in the plugins? otherwise each argument addition will require a change to both the cloudformation cli and the plugin. Would be good to structure it in a way to where an argument addition on the plugin just means one change to the plugin.

2020-09-29 00:02 UTC, jotompki approved these changes

2020-09-29 00:02 UTC, jotompki commented on tests/plugin/parser_test.py
> +    assert args.use_docker is True
nit: `assert args.use_docker`

2020-09-29 00:02 UTC, jotompki commented on tests/plugin/parser_test.py
> +    assert args.use_docker is False
same here can simplify

2020-10-15 18:08 UTC, jaymccon approved these changes

2020-10-15 18:36 UTC, eduardomourar commented on python/rpdk/python/codegen.py
>          project.settings["use_docker"] = self._use_docker
We should make this `useDocker` for consistency with `protocolVersion` and JSON convention, right?

2020-10-15 22:44 UTC, ammokhov approved these changes

2020-10-15 23:38 UTC, merged