Added a method to provide plugin information that is included in artifact zip
aws-cloudformation/cloudformation-cli-python-plugin pull request #167
Opened 2021-09-30 18:49 UTC by priyap286

*Description of changes:*
Added a method to provide plugin information that is included in artifact zip.
Plugin information includes,

plugin-tool-version - The version of the cli tool
plugin-name - "java"/"python"/"go". Here it is "python"

I also updated the mypy version and made few other changes based on pre-commit run.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-30 18:59 UTC, priyap286 commented on .pre-commit-config.yaml
> +  rev: v0.790
Upgraded mypy because of python/mypy#9916.

2021-09-30 18:59 UTC, priyap286 commented on src/cloudformation_cli_python_lib/recast.py
> +    if cls is typing.Any:
Made this change because of pylint error,
W0143: Comparing against a callable, did you omit the parenthesis? (comparison-with-callable)

2021-09-30 18:59 UTC, priyap286 commented on src/cloudformation_cli_python_lib/recast.py
> +        return typing.ForwardRef
removed "# type: ignore" because of mypy complaining of `unused 'type: ignore' comment `

2021-09-30 19:08 UTC, ammokhov requested changes

2021-09-30 21:59 UTC, omkhegde approved these changes
Please make sure this change works locally as well

2021-10-12 23:41 UTC, priyap286 commented on python/rpdk/python/codegen.py
> +    # pylint: disable=unused-argument
Added comments as to why the argument project is part of the method signature but not used. Link to code in cloudformation-cli, https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/project.py#L546

2021-10-19 19:23 UTC, ammokhov commented on python/rpdk/python/codegen.py
> +from . import __version__
why?

2021-10-21 02:35 UTC, merged